### ISSUE TITLE
"QA" test references to failing tests disappear and reappear again on staging dashboards

### ISSUE THREAD

**Issue by okurz** [openSUSE-Team/obs_factory#49]
## observation
The staging dashboards have entries like "QA: firefox_audio" with an href link to failing openqa test runs. Under so far unclear circumstances the tag disappears and then reappears again with a reference to the same test run.

Probably the following happens:

* tests fail and are reported
* there is an OBS submission causing a build
* dashboard refreshes and obsoletes the old entries
* before build can finish OBS submission is superseeded (or aborted?)
* dashboard is un-obsoleting the old test fail reports and shows them again

## expected result
The issue persists until a subsequent test has been triggered and completed either reproducing the problem -> shows up again but with new test reference or verifing issue fixed -> disappears. An alternative would be to remove it as soon as a new test is triggered expected to verify the fix.

**Comment by coolo** [comment]
If OBS builds we don't show any QA results. Only once OBS is done with its job

**Comment by okurz** [comment]
Sometimes I have problems to understand what I am supposed to do with your comments aka. "So what?"

**Comment by coolo** [comment]
To make it concrete: the staging dashboard is for the staging manager, not for QA. As such your expected result is out of the specification and as such INVALID.

**Comment by okurz** [comment]
But what is the "QA" field for? e.g. on https://build.opensuse.org/project/staging_projects/openSUSE:Factory/ it is referencing openQA staging tests. If you are refering to "QA" as in "QA departement" I care because "PQA" is asked to review failing staging tests to confirm it is not an "openQA issue" aka. "false positive".

**Comment by coolo** [comment]
The QA is for "fails in openQA, not in OBS". We link failing packages from the same spot.

**Comment by okurz** [comment]
That's all nice and dandy but … ah, nevermind, I will work around that issue
