### ISSUE TITLE
42.2 staging dashboard uses Factory names

### ISSUE THREAD

**Issue by lnussel** [openSUSE-Team/obs_factory#57]
The 42.2 staging dashboard (https://build.opensuse.org/project/staging_projects/openSUSE:Leap:42.2) opens openQA like https://openqa.opensuse.org/tests?hoursfresh=24&match=Staging:A instead of match="42:S:A"

**Comment by coolo** [comment]
https://github.com/openSUSE-Team/obs_factory/pull/58 is untested, but should help here
